### ISSUE TITLE
Djeeta's Warpath

### ISSUE THREAD

**Issue by Tsuyara** [Jay13Jeong/GBFR-logs-anti-cheat#7]
On the current release version and on the pre-release version this triggers a dmg cheat, even with the programmed in djeetaBuff. (77350 is decidedly too low, her attack can reach 85k with glass cannon and 81.04k without, and will in your usual Djeeta build with just 1 alpha 2 gamma hit 79.2k)
It's an innate 10% damage buff that can stack with things like Katalina's 25%.
Also curious if this can handle Roll of the Die.

**Comment by Jay13Jeong** [comment]
@Tsuyara 
Thank you for reporting! Due to the complexity of damage interactions between characters, achieving 100% accuracy in handling them is challenging. I have made adjustments to reflect this as much as possible and have uploaded the [updated version](https://github.com/Jay13Jeong/GBFR-logs-anti-cheat/releases).
